#!/usr/bin/env bash
# Concatenate the modular installer into one standalone script for GitHub Releases.
# Usage: pack.sh [outfile]
#   outfile defaults to stdout.
# shellcheck disable=SC2016
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${1:-}"

INSTALL_LIBS=(
  lib/common.sh
  lib/logging.sh
  lib/ui.sh
  lib/state.sh
  lib/system.sh
  lib/docker.sh
  lib/dependencies.sh
  lib/storage.sh
  lib/network.sh
  lib/config.sh
  lib/health.sh
)

CTL_LIBS=(
  lib/common.sh
  lib/logging.sh
  lib/docker.sh
  lib/system.sh
  lib/storage.sh
  lib/network.sh
  lib/state.sh
  lib/health.sh
  lib/ctl_update.sh
)

emit_lib() {
  local rel="$1"
  printf '\n# ---- %s ----\n' "${rel}"
  # Drop shebang if present; keep shellcheck directives.
  sed '/^#!/d' "${ROOT}/${rel}"
  printf '\n'
}

pack_ctl() {
  cat <<'HDR'
#!/usr/bin/env bash
# Generated by installer/pack.sh — Folium management CLI.
set -euo pipefail
FOLIUM_PACKED=1
HDR
  local rel
  for rel in "${CTL_LIBS[@]}"; do
    emit_lib "${rel}"
  done
  sed '/^#!/d' "${ROOT}/folium-ctl.sh"
}

pack_installer() {
  cat <<'HDR'
#!/usr/bin/env bash
# Generated by installer/pack.sh — standalone Folium installer.
# Source lives in installer/{install.sh,lib,folium-ctl.sh}. Do not edit this file.
set -euo pipefail
FOLIUM_PACKED=1
HDR
  local rel
  for rel in "${INSTALL_LIBS[@]}"; do
    emit_lib "${rel}"
  done

  printf '\nfolium_install_packed_ctl() {\n'
  printf '  local tmp\n'
  printf '  tmp="$(mktemp)"\n'
  printf "  cat >\"\${tmp}\" <<'FOLIUM_PACKED_CTL_EOF'\n"
  pack_ctl
  printf 'FOLIUM_PACKED_CTL_EOF\n'
  cat <<'FOOT'
  chmod 700 "${tmp}"
  mkdir -p "${FOLIUM_INSTALL_DIR}/installer"
  cp -a "${tmp}" "${FOLIUM_INSTALL_DIR}/installer/folium"
  run_root install -m 755 "${tmp}" /usr/local/bin/folium
  rm -f "${tmp}"
}
FOOT

  printf '\n# ---- install.sh ----\n'
  sed '/^#!/d' "${ROOT}/install.sh"
}

if [[ -n "${OUT}" ]]; then
  pack_installer >"${OUT}"
  chmod 755 "${OUT}"
else
  pack_installer
fi
